title: Bukit Panjang Government High School
url: https://www.bpghs.moe.edu.sg
favicon: /images/fav.png
colors:
  primary-color: "#9b4d6a"
  secondary-color: "#318e54"
  media-colors:
    - title: media-color-one
      color: "#9b4d6a"
    - title: media-color-two
      color: "#9b4d6a"
    - title: media-color-three
      color: "#9b4d6a"
    - title: media-color-four
      color: "#9b4d6a"
    - title: media-color-five
      color: "#9b4d6a"
resources_name: Resources
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2ojqoen9ve22n.amplifyapp.com/
prod: https://master.d2ojqoen9ve22n.amplifyapp.com/
shareicon: /images/logo.jpeg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
